function anonymizegui()

    %Get the user`s screen size to help centering the interface
    screenSize = get(0,'ScreenSize');

    %Main window
    mainFigure = figure('Tag',mfilename,...
        'MenuBar','None',...        
        'IntegerHandle','off',...
        'Units', 'Normalized',...
        'Resize','on',...
        'NumberTitle','off',...
        'Name',sprintf('Anonymization Tool'),...
        'Visible','on',...
        'Position',[screenSize(1) / 2 - 0.2, screenSize(2) / 2 - 0.1, 0.4, 0.15] ,... %400,50,1050,700
        'Tag','mainfig');
    
    figureBackGroundColor = get(mainFigure, 'Color');
    
    folderLabel = uicontrol('Parent', mainFigure,...
        'String', 'Folder:',...
        'Style', 'Text',...
        'FontWeight', 'Bold',...
        'Units', 'Normalized',...
        'Backgroundcolor', figureBackGroundColor,...
        'Position', [0.01, 0.8, 0.1, 0.12]);
    
    folderEdit = uicontrol('Parent', mainFigure,...
        'Style', 'Edit',...
        'Backgroundcolor', [1 1 1],...
        'Units', 'Normalized',...
        'Position', [0.12, 0.73, 0.87, 0.25],...
        'Enable', 'Inactive',...
        'Tag', 'folderEdit');
    
    loadButton = uicontrol('Parent',mainFigure,...
        'Units', 'Normalized',...
        'Position', [0.35, 0.25, 0.15, 0.25],...
        'String', 'Load',...
        'Callback', @loadFolder);
    
    runButton = uicontrol('Parent',mainFigure,...
        'Units', 'Normalized',...
        'Position', [0.55, 0.25, 0.15, 0.25],...
        'String', 'Run',...
        'Tag', 'runButton',...
        'Enable', 'Off',...
        'Callback', @runCallback);
    
    handles.graph = guihandles(mainFigure);
    guidata(mainFigure, handles)
    
                          
end


function loadFolder(hObject, eventdata)
    handles = guidata(hObject);
    
    filesFolder = uigetdir('Select a folder');
    
    if filesFolder
        set(handles.graph.folderEdit, 'String', filesFolder);
        set(handles.graph.runButton, 'Enable', 'On');
        handles.data.filesFolder = filesFolder;
        guidata(hObject, handles);
    end

end

function runCallback(hObject, eventdata)
    handles = guidata(hObject);
    filesFolder = handles.data.filesFolder;
    listFiles = dir(filesFolder);
end

function endswith(fileName)

end
